config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: {
    minimum: 6,
    too_short: 'Minimum required characters count is 6!'
  }
  validates :movie, uniqueness: { scope: :list }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :poster_url, presence: true, allow_blank: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :list, optional: true
  has_many :bookmarks

  def destroy
    raise 'Cannot delete a movie' unless bookmarks.count.zero?

    super
  end

  validates :overview, uniqueness: true, presence: true, allow_blank: false
  validates :title, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_movie, :find_list, except: [:destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def find_movie
    @movie = Movie.find(params[:movie_id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      redirect_to lists_path
    end
  end

  def list_params
    params.require(:list).permit(:name, :poster_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render './navbar' %>

<div class="container">
  <div class="banner-text">
    <h1>Create your own watchlist</h1>
    <button id="create_button">New list</button>
    <%= form_for(@list) do |f| %>
      <div class="form_field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form_field">
        <%= f.label :poster_url %>
        <%= f.text_field :poster_url %>
      </div>
      <%= f.submit "Create now!", class:"form_button" %>
    <% end %>
  </div>
</div>
<div>
  <h4>My lists</h4>
  <div class="lists">
    <% @lists.each do |list| %>
    <div class="list" <% unless list.poster_url.nil? %>
        style="background-image: url(<%= list.poster_url %>); background-size: cover;"
      <% end %>>
      <h4><%= link_to list.name, list_path(list) %></h4>
    </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'index' %>

app/views/lists/show.html.erb
<%= render './navbar' %>

<div class="banner_list" <% unless @list.poster_url.nil? %>
    style="background-image: url(<%= @list.poster_url %>); background-size: cover;"
  <% end %>>
  <h1><%= @list.name %></h1>
</div>


 <button id="add_movie_button">Add a movie</button>
    <%= form_for @bookmark, :url => list_bookmarks_path(@list) do |f| %>
      <select name="movie_id" id="movie-select" class="movie-select">
          <option value="">--Please choose a movie--</option>
          <% @movies.each do |movie| %>
          <option value="<%= movie.id %>"><%= movie.title %></option>
          <% end %>
      </select>
  <%= f.label :comment, class:"comment_field" %>
  <%= f.text_field :comment %>

      <%= f.submit "Add a movie!", class:"form_button bookmark_movie_button" %>
    <% end %>


<div class="movies">
    <% @list.movies.each do |movie| %>
    <div class="movie">
      <img class="poster" src="<%= movie.poster_url %>" alt="movie_poster" />
    <h4><%= movie.title %> * <%= movie.rating %></h4>
    <p><%= movie.overview %></p>
    <% unless movie.bookmarks.first.nil? %>
      <span class="review">&ldquo; <%= movie.bookmarks.first.comment %></span>
    <% end %>
    <%= link_to "Delete", list_bookmark_path(@list, movie.bookmarks.first), class:"delete_link", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>
</div>



<%= javascript_pack_tag 'show' %>